application: ascii-chan-1337
version: 1
runtime: python27
api_version: 1
threadsafe: True

handlers:
- url: .*
  script: ascii-chan.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
